language: ruby
sudo: false
rvm:
  - "1.8.7"
  - "1.9.3"
  - "2.0.0"
  - "2.1"
  - "2.2"
  - jruby-18mode
  - jruby-19mode
  - jruby-20mode
  - jruby-head
  - rbx
  - rbx-2
before_install:
  - gem query -i -n ^bundler$ > /dev/null || gem install --no-ri --no-rdoc bundler
notifications:
  email:
    - uwe@kubosch.no
